---
- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: fcrepo_installed_java_version
  changed_when: false

- assert:
    that: 
      - "fcrepo_installed_java_version.stdout is version(fcrepo_required_java_version, '>=')"

- name: add fcrepo user
  user:
    name:   "{{ fcrepo_user }}"
    shell:  "/bin/bash"

  # NOTE: remove filename (or anything else) if it is included after the checksum
- name: get fedora checksum
  set_fact:
    fcrepo_checksum: "{{ fcrepo_checksum_algo }}:{{ item | regex_replace('\\s+.*', '') }}"
  with_url: "{{ fcrepo_checksum_url }}"

- name: get fedora
  get_url:
    url:      "{{ fcrepo_download_url }}"
    dest:     "{{ fcrepo_download_dir }}"
    checksum: "{{ fcrepo_checksum }}"
    owner:    "{{ fcrepo_user }}"
    group:    "{{ fcrepo_user }}"
  register: got_fedora

- name: remove previously deployed fedora, if we have a new war
  file:
    dest: "{{ fcrepo_webapps_dir }}/fedora"
    state: absent
  when: got_fedora.changed

- name: check for deployed fedora
  stat:
    path: "{{ fcrepo_webapps_dir }}/fedora"
  register: deployed_fedora

- name: deploy fedora
  command: "cp {{ fcrepo_download_dir }}/fcrepo-webapp-{{ fcrepo_version }}.war {{ fcrepo_webapps_dir }}/fedora.war"
  when: not deployed_fedora.stat.exists
  notify: restart tomcat

- name: create fedora directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ fcrepo_user }}"
    group: "{{ fcrepo_user }}"
  with_items:
    - "{{ fcrepo_config_dir }}"
    - "{{ fcrepo_home }}"
    - "{{ fcrepo_log_dir }}"

- name: create tomcat service directory for additional configuration
  file:
    path: "/etc/systemd/system/tomcat.service.d"
    state: directory

- name: set fedora system properties
  template:
    src: "fcrepo.conf.j2"
    dest: "/etc/systemd/system/tomcat.service.d/fcrepo.conf"
  notify: restart tomcat

- name: configure fedora logging
  template:
    src:  "logback.xml.j2"
    dest: "{{ fcrepo_config_dir }}/logback.xml"
  notify: restart tomcat
